# Generated by Django 6.0.3 on 2026-03-15 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('general', 'General Support'), ('anxiety', 'Anxiety Management'), ('stress', 'Academic Stress'), ('depression', 'Depression Support'), ('crisis', 'Crisis Intervention'), ('greeting', 'Greeting/Introduction'), ('followup', 'Follow-up Questions')], default='general', max_length=50)),
                ('template_content', models.TextField()),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('times_used', models.IntegerField(default=0)),
                ('avg_rating', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='openai_inte_categor_417c70_idx'), models.Index(fields=['name'], name='openai_inte_name_731574_idx')],
            },
        ),
        migrations.CreateModel(
            name='APICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('model_used', models.CharField(max_length=50)),
                ('provider', models.CharField(default='github-models', max_length=20)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('response_time_ms', models.IntegerField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('rate_limited', 'Rate Limited'), ('timeout', 'Timeout'), ('auth_error', 'Authentication Error')], max_length=20)),
                ('prompt_preview', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('conversation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_calls', to='chat.conversation')),
                ('message', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_log', to='chat.message')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='openai_inte_timesta_dbf6f7_idx'), models.Index(fields=['status'], name='openai_inte_status_abf83f_idx'), models.Index(fields=['conversation'], name='openai_inte_convers_cb1fea_idx'), models.Index(fields=['provider'], name='openai_inte_provide_388c7c_idx')],
            },
        ),
    ]
