# Generated by Django 6.0.3 on 2026-03-15 15:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUserSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('hashed_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('encrypted_data', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['session_id'], name='accounts_an_session_984ef1_idx'), models.Index(fields=['expires_at'], name='accounts_an_expires_75aa18_idx'), models.Index(fields=['last_activity'], name='accounts_an_last_ac_96eac6_idx')],
            },
        ),
    ]
