# Generated by Django 6.0.3 on 2026-03-15 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrisisKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('severity_level', models.IntegerField(choices=[(1, 'Low - Concerning keywords'), (2, 'Medium - Strong indicators'), (3, 'High - Immediate attention'), (4, 'Critical - Immediate intervention required')], default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['word'], name='emergency_c_word_f99d28_idx'), models.Index(fields=['severity_level', 'is_active'], name='emergency_c_severit_88c7e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmergencyResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('text_line', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('region', models.CharField(choices=[('global', 'Global'), ('us', 'United States'), ('uk', 'United Kingdom'), ('ca', 'Canada'), ('au', 'Australia'), ('ng', 'Nigeria')], default='global', max_length=20)),
                ('languages', models.CharField(default='English', max_length=200)),
                ('hours_available', models.CharField(default='24/7', max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['region', 'priority', 'name'],
                'indexes': [models.Index(fields=['region', 'priority'], name='emergency_e_region_366776_idx'), models.Index(fields=['is_available'], name='emergency_e_is_avai_77eb2a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CrisisFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('severity', models.IntegerField(choices=[(1, 'Low - Concerning keywords'), (2, 'Medium - Strong indicators'), (3, 'High - Immediate attention'), (4, 'Critical - Immediate intervention required')], default=1)),
                ('status', models.CharField(choices=[('detected', 'Detected - Not escalated'), ('escalated', 'Escalated to human'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='detected', max_length=20)),
                ('detection_method', models.CharField(default='keyword', max_length=50)),
                ('matched_keywords', models.TextField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_to', models.CharField(blank=True, max_length=100, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crisis_flags', to='chat.conversation')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crisis_flag', to='chat.message')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crisis_flags', to='accounts.anonymoususersession')),
            ],
            options={
                'ordering': ['-severity', 'detected_at'],
                'indexes': [models.Index(fields=['status', 'severity'], name='emergency_c_status_c56a8e_idx'), models.Index(fields=['detected_at'], name='emergency_c_detecte_283624_idx'), models.Index(fields=['session'], name='emergency_c_session_cb66dd_idx')],
            },
        ),
    ]
