# Generated by Django 6.0.3 on 2026-03-15 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Resource categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, max_length=300)),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('exercise', 'Exercise'), ('tip', 'Quick Tip'), ('guided', 'Guided Practice'), ('external', 'External Link')], default='article', max_length=20)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='resources/')),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.IntegerField(default=0)),
                ('helpful_count', models.IntegerField(default=0)),
                ('not_helpful_count', models.IntegerField(default=0)),
                ('avg_rating', models.FloatField(blank=True, null=True)),
                ('categories', models.ManyToManyField(related_name='resources', to='resources.resourcecategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='resources', to='resources.resourcetag')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_score', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Neutral'), (4, 'Good'), (5, 'Excellent')])),
                ('note', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('day_of_week', models.IntegerField()),
                ('time_of_day', models.TimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mood_entries', to='chat.conversation')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to='accounts.anonymoususersession')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['session', '-recorded_at'], name='resources_m_session_4b6b06_idx'), models.Index(fields=['mood_score'], name='resources_m_mood_sc_7327f4_idx'), models.Index(fields=['recorded_at'], name='resources_m_recorde_dc73c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResourceInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'Viewed'), ('helpful', 'Marked Helpful'), ('not_helpful', 'Marked Not Helpful'), ('share', 'Shared'), ('save', 'Saved')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mood_at_time', models.IntegerField(blank=True, choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Neutral'), (4, 'Good'), (5, 'Excellent')], null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_interactions', to='accounts.anonymoususersession')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='resources.resourceitem')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['session', 'interaction_type'], name='resources_r_session_95e2e1_idx'), models.Index(fields=['resource', '-timestamp'], name='resources_r_resourc_109ec1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='resourceitem',
            index=models.Index(fields=['resource_type', 'is_published'], name='resources_r_resourc_864d84_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceitem',
            index=models.Index(fields=['-published_at'], name='resources_r_publish_f2b462_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceitem',
            index=models.Index(fields=['-view_count'], name='resources_r_view_co_b69402_idx'),
        ),
    ]
